version = 0.1

[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "QuestionsTableName=\"adtech_questions\" LeaderboardTableName=\"leaderboard\""
image_repositories = []
